name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Déclenche l'action lors d'un push sur la branche `main`

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Créer le dossier public (c'est où les fichiers seront générés)
      - name: Create public folder
        run: mkdir public

      # Étape 3 : Copier les fichiers HTML dans le dossier public
      - name: Copy HTML files to public folder
        run: cp -r html/* public/

      # Étape 4 : Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Utilisation du token par défaut de GitHub Actions
          publish_dir: ./public  # Dossier à publier sur GitHub Pages
