name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Assure-toi que c'est la dernière version

      - name: Setup public directory
        run: mkdir -p public

      - name: Generate index.html
        run: |
          echo '<!DOCTYPE html>
          <html lang="fr">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Fichiers disponibles</title>
            <style>
              body { font-family: Arial, sans-serif; text-align: center; padding: 20px; }
              ul { list-style-type: none; padding: 0; }
              li { margin: 10px 0; }
              a { text-decoration: none; font-size: 18px; color: blue; }
              .back-button { margin-top: 20px; display: inline-block; padding: 10px 20px; background: grey; color: white; text-decoration: none; border-radius: 5px; }
            </style>
          </head>
          <body>
          <h1>📂 Fichiers disponibles</h1>
          <ul>' > public/index.html
          for file in html/*.html; do
            name=$(basename "$file")
            echo "<li><a href=\"$name\">$name</a></li>" >> public/index.html
          done
          echo '</ul></body></html>' >> public/index.html

      - name: Copy HTML files
        run: cp html/*.html public/

      - name: Add "Retour à la liste" button
        run: |
          for file in public/*.html; do
            if [ "$(basename "$file")" != "index.html" ]; then
              sed -i 's|</body>|<a class="back-button" href="index.html">Retour à la liste</a></body>|' "$file"
            fi
          done

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v2  # Correct, c'est la version v2 ici

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2  # Correct aussi
