name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up site
        run: |
          mkdir -p public
          cat <<'EOF' > public/index.html
          <!DOCTYPE html>
          <html lang="fr">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Fichiers disponibles</title>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/quarto-cli@latest/resources/quarto-web.css">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/quarto-cli@latest/resources/themes/slate/slate.css">
            <style>
            body {
              background-color: #000;
              margin: 0;
              padding: 20px;
              color: white;
            }
            .container {
              max-width: 600px;
              max-height: 80vh;
              padding: 30px;
              background: #222;
              border-radius: 10px;
              box-shadow: 0px 4px 10px rgba(255, 255, 255, 0.1);
              overflow-y: auto;
            }
            h1 {
              font-size: 2rem;
              margin-bottom: 20px;
              color: white;
            }
            ul {
              list-style-type: none;
              padding: 0;
            }
            li {
              margin: 10px 0;
              padding: 10px;
              border-bottom: 1px solid #555;
            }
            a {
              text-decoration: none;
              font-weight: bold;
              color: #1e90ff;
            }
            a:hover {
              text-decoration: underline;
            }
            .description {
              color: #bbb;
              margin-top: 5px;
              font-size: 0.9em;
            }
            </style>
          </head>
          <body class="quarto-slate">
          <div class="container">
            <h1>📂 Emploi et Spécialité de formation</h1>
            <p style="text-align: center;">Camille Favre</p>
            <ul>
          EOF

          for file in html/*.html; do
            base=$(basename "$file" .html)
            echo "<li><a href=\"$base.html\">$base</a>" >> public/index.html
            if [ -f "html/$base.txt" ]; then
              description=$(cat "html/$base.txt")
              echo "<div class=\"description\">$description</div>" >> public/index.html
            fi
            echo "</li>" >> public/index.html
          done

          echo '</ul></div></body></html>' >> public/index.html
          cp html/*.html public/

          for file in public/*.html; do
            if [ "$(basename "$file")" != "index.html" ]; then
              perl -i -pe 's{</\s*body\s*>}{<div style="text-align:center; position:fixed; bottom:20px; left:50%; transform:translateX(-50%); z-index:9999;"><a href="index.html" style="display:inline-block; padding:10px 20px; font-size:16px; color:#fff; background-color:#6c757d; border:none; border-radius:5px; text-decoration:none;">Retour à la liste</a></div></body>}i' "$file"
            fi
          done

      - name: Deploy to GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          path: public

      - name: Deploy
        uses: actions/deploy-pages@v1
